### ISSUE TITLE
Error related to log file

### ISSUE THREAD

**Issue by PavanMudigondaTR** [saucelabs/sauce-connect-action#68]
Getting Error Related to Log File. Could you please let us know if we are doing something wrong or if there is defect on this action ?
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/86745613/213772040-834b8d5e-be30-4dd3-9cde-f417e3386211.png">

version: latest v2.3.1

**Comment by waggledans** [comment]
solved in https://github.com/saucelabs/sauce-connect-action/pull/71

**Comment by PavanMudigondaTR** [comment]
@waggledans  we are still getting same error with new version.

**Comment by waggledans** [comment]
@PavanMudigondaTR, did you try v2.3.2 or  v2.3.3? I think the issue wasn't with the log file but smth with your config file and the error message was misleading.
Can you post here the error that you see and, also, your config file?  I think the SC process exits immediately and we just don't capture the error message.

**Comment by PavanMudigondaTR** [comment]
@waggledans we will try again this week and let you know

**Comment by waggledans** [comment]
@PavanMudigondaTR I actually tried to use a [bad config](https://github.com/saucelabs/sauce-connect-action/actions/runs/4226060853/jobs/7339089650) to check what pluigin log looks like and, unlike before, u're supposed to see an ACTUAL error if SC failed to start. For example:

```
Warning: Sauce connect log: 2023-02-20 18:09:46.338 [1713] [CLI] [fatal] '--rest-url' is not allowed with '--region'. Please visit https://docs.saucelabs.com/basics/data-center-endpoints/ for more information.
```
